#!/bin/bash
set -e

testname="$1"
results="testcases/${testname}.results"
rm -rf "$results"
mkdir -p "$results"
cd "$results"
if "../${testname}.sh" > stdout.txt 2> stderr.txt; then
    touch success
else
    msg="Exited with error code $?"
    echo "$msg" > fail
    echo -e "\\e[31m=== Test $testname: $msg\\e[0m"
    exit 1
fi
