#!/bin/bash
set -e

testname="$1"
results="testcases/${testname}.results"
rm -rf "$results"
mkdir -p "$results"
cd "$results"
set +e
"../${testname}.sh" > stdout.txt 2> stderr.txt
ec="$?"
set -e
if [ "$ec" == 0 ] && ! [ -e fail ]; then
    touch success
else
    echo "Test $testname exited with error code $ec" >> fail
    exit 1
fi
