#!/bin/bash
set -e

hashofscreenshot() {
    file="screenshot-${1}.png"
    [ -e "$file" ]
    < "$file" png2ff | sha256sum | cut -d " " -f 1
}

if [ "$(hashofscreenshot "$1")" == "$(hashofscreenshot "$2")" ]; then
    echo FAIL: Screenshots "$1" and "$2" match, but they should differ.
    exit 1
else
    echo Screenshots "$1" and "$2" differ, as expected.
    exit 0
fi
