#!/bin/bash
set -e

echo-green () {
    if [ -t ]; then
        echo -e "\\e[32m$@\\e[0m"
    else
        echo "$@"
    fi
}

echo-red () {
    if [ -t ]; then
        echo -e "\\e[31m$@\\e[0m"
    else
        echo "$@"
    fi
}

count="$1"
[ 1 -le "$count" ]
docker run -v "`pwd`/testcases":/home/user/testcases --init `cat test-runner.iid` generate-tests "$count" &
process=$!
echo-green "=== Begin generating $count tests in docker process $process"

interrupt() {
    echo-red "Got interrupt, sending SIGTERM to docker process $process"
    kill -s SIGTERM "$process"
    exit 2
}

trap interrupt INT

if wait "$process"; then
    echo-green "=== Generating $count tests: Done"
    echo-green "=== Test $testname: Done"
else
    echo-red "=== Generating $count tests: FAIL."
    exit 1
fi
