#!/bin/bash
set -e

echo-green () {
    if [ -t ]; then
        echo -e "\\e[32m$@\\e[0m"
    else
        echo "$@"
    fi
}

echo-red () {
    if [ -t ]; then
        echo -e "\\e[31m$@\\e[0m"
    else
        echo "$@"
    fi
}

testname="$1"
[ -n "$testname" ]
[ -e "testcases/$testname.sh" ]
docker run -v "`pwd`/testcases":/home/user/testcases --init `cat test-runner.iid` run-test "$testname" &
process=$!
echo-green "=== Test $testname: Begin running in docker process $process"

interrupt() {
    echo-red "Got interrupt, sending SIGTERM to docker process $process"
    kill -s SIGTERM "$process"
    exit 2
}

trap interrupt INT

if wait "$process"; then
    echo-green "=== Test $testname: Done"
else
    echo-red "=== Test $testname: FAIL."
    exit 1
fi
